// ════════════════════════════════════════════════════════════════════════════
//  SITE CONFIG — single source of truth for all content, SEO, and schema
//  Edit this file; nothing in /components needs to change for content updates
// ════════════════════════════════════════════════════════════════════════════

export const siteConfig = {
  // ── Identity ─────────────────────────────────────────────────────────────
  name:       "Tommy Rosario",
  firstName:  "Tommy",
  lastName:   "Rosario",
  role:       "Sr. Frontend Engineer",
  favicon:    "/favicon.ico",
  icons: {
      icon16: "/favicon-16x16.png",
      icon32: "/favicon-32x32.png",
      apple:  "/apple-touch-icon.png",
      android192: "/android-chrome-192x192.png",
      android512: "/android-chrome-512x512.png",
  },

  /** Used in JSON-LD and SEO copy — all professional aliases */
  roleAliases: [
    "React Developer",
    "JavaScript Developer",
    "TypeScript Developer",
    "UI Engineer",
    "Web Application Developer",
    "Freelance Frontend Developer",
  ],
  tagline:    "I build things for the web.",
  location:   "Jersey Shore, NJ",
  availableForWork: true,

  // ── Bio (naturally keyword-rich, readable) ────────────────────────────────
  bio: "Senior Frontend Engineer with 15+ years building high-performance, scalable web applications for consumer platforms and internal enterprise tools. Expert in React, Next.js, TypeScript, Angular, and Vue, with a strong foundation in modern CSS, Tailwind, and design systems.",
  bioExtended:
    "Known for leading large-scale frontend migrations, improving performance and SEO, and delivering fast, polished user experiences that directly support business growth. Comfortable working across product, design, and data teams to ship features that scale.",
  bioHighlights: [
    "15+ years building production web applications",
    "Expert in React, Next.js, TypeScript, Angular & Vue",
    "Led large-scale frontend migrations & performance improvements",
    "Cross-functional work across product, design & data teams",
  ],

  // ── Contact ───────────────────────────────────────────────────────────────
  email:         "tomjasonrosario@gmail.com",
  github:        "https://github.com/tjrosario",
  linkedin:      "https://www.linkedin.com/in/tommy-rosario-65771711/",
  twitter:       "https://twitter.com/tommyrosario",
  twitterHandle: "@tommyrosario",

  // ── SEO / OG ──────────────────────────────────────────────────────────────
  siteUrl:  "https://tommyrosario.me",
  ogImage:  "/og",
  /** Title template for sub-pages */
  titleTemplate: "%s | Tommy Rosario — Frontend Developer",
  /** Primary meta description — ≤160 chars */
  metaDescription:
    "Tommy Rosario is a freelance frontend developer and React specialist in New York. Available to hire for web application development, UI engineering, and design systems.",

  // ── JSON-LD extras ────────────────────────────────────────────────────────
  knowsAbout: [
    "React", "Next.js", "TypeScript", "Angular", "Vue",
    "Tailwind CSS", "Design Systems", "Core Web Vitals",
    "SEO", "Headless CMS", "GraphQL", "Algolia", "Contentful",
    "OpenAI APIs", "Node.js", "PostgreSQL", "Stripe",
    "Frontend Architecture", "Web Performance",
  ],

  // ── Skills ────────────────────────────────────────────────────────────────
  coreStrengths: [
    "React & Next.js",
    "TypeScript",
    "Design Systems",
    "Core Web Vitals",
    "AI & Automation",
  ],
  skillGroups: [
    {
      label: "Frontend",
      skills: [
        "React", "Next.js", "TypeScript", "Angular", "Vue",
        "Tailwind CSS", "Modern CSS", "SASS",
      ],
    },
    {
      label: "Architecture & Performance",
      skills: [
        "Design Systems", "Core Web Vitals", "SEO",
        "Headless CMS", "GraphQL", "Component Architecture",
      ],
    },
    {
      label: "AI & Automation",
      skills: [
        "OpenAI APIs", "Claude", "Microsoft Copilot",
        "AI-Assisted Workflows",
      ],
    },
    {
      label: "Search & CMS",
      skills: [
        "Algolia", "Contentful",
      ],
    },
    {
      label: "Backend & Tooling",
      skills: [
        "Node.js", "PostgreSQL", "Stripe", "PayPal",
        "Azure Static Web Apps", "Jenkins",
      ],
    },
  ],

  // ── Projects ──────────────────────────────────────────────────────────────
  projects: [
    {
      name: "ChatGPT Reviews",
      slug: "chatgpt-reviews",
      description:
        "A React application that uses the OpenAI API to generate AI-powered product reviews on demand. Users can request reviews for any product and receive detailed, structured feedback generated by GPT — demonstrating practical AI integration in a polished TypeScript + Tailwind UI.",
      stack: ["React", "TypeScript", "Tailwind CSS", "OpenAI API", "Create React App"],
      highlights: [
        "OpenAI GPT integration for dynamic review generation",
        "Fully typed with TypeScript",
        "Tailwind CSS utility-first styling",
      ],
      github: "https://github.com/tjrosario/chatgpt-reviews",
      live:   null,
    },
    {
      name: "Bite",
      slug: "bite",
      description:
        "A food discovery and restaurant browsing app built with Next.js App Router. Features a Zustand-powered cart and state management layer, fully typed data models, and a clean mobile-first UI deployed to Vercel. Structured around reusable components with a clear separation of data, store, and UI layers.",
      stack: ["Next.js", "TypeScript", "Tailwind CSS", "Zustand", "Vercel"],
      highlights: [
        "Next.js App Router with TypeScript",
        "Zustand for global cart & UI state",
        "Live on Vercel at bite-eight.vercel.app",
      ],
      github: "https://github.com/tjrosario/bite",
      live:   "https://bite-eight.vercel.app",
    },
    {
      name: "Ticket Purchase",
      slug: "ticket-purchase",
      description:
        "A mock event ticketing checkout UI built with React and Vite. Demonstrates a clean, component-driven purchase flow — seat selection, order summary, and checkout — with a focus on UI state management and fast local dev iteration using Vite's instant HMR.",
      stack: ["React", "JavaScript", "Vite", "CSS"],
      highlights: [
        "Vite-powered dev environment with instant HMR",
        "Component-driven checkout flow",
        "Clean seat selection & order summary UI",
      ],
      github: "https://github.com/tjrosario/ticket-purchase",
      live:   null,
    },
    {
      name: "Brewery App",
      slug: "brewery-app",
      description:
        "A brewery search and discovery app powered by the Open Brewery DB public API. Built with React's Context and Hooks APIs for state management — no external state library — allowing users to search and filter breweries across the US by name, type, and city. A clean exercise in idiomatic React patterns.",
      stack: ["React", "TypeScript", "Context API", "Hooks", "Open Brewery DB API"],
      highlights: [
        "React Context + Hooks for state — no Redux",
        "Multi-criteria brewery search & filtering",
        "20 pull requests worth of iterative development",
      ],
      github: "https://github.com/tjrosario/brewery-app",
      live:   null,
    },
  ],

  // ── Ticker marquee keywords ───────────────────────────────────────────────
  tickerWords: [
    "React & Next.js",
    "TypeScript",
    "Angular & Vue",
    "Design Systems",
    "Core Web Vitals",
    "GraphQL",
    "Algolia",
    "Contentful",
    "OpenAI APIs",
    "Node.js",
  ],
} as const;

export type SiteConfig = typeof siteConfig;
export type Project    = typeof siteConfig.projects[number];