# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages 📦
      run: npm ci
    - name: Run build ⚙️
      run: npm run build --if-present
      env:
        NEXT_PUBLIC_ABSOLUTE_PATH: https://tjrosario.github.io/portfolio
        NEXT_PUBLIC_BASE_PATH: /portfolio
    - name: Run export 📁
      run: npm run export
      env:
        NEXT_PUBLIC_ABSOLUTE_PATH: https://tjrosario.github.io/portfolio
        NEXT_PUBLIC_BASE_PATH: /portfolio
    - name: Add .nojekyll file
      run: touch ./out/.nojekyll # Creates a file telling Github not to build the project using Jekyll
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: out # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
